var post = require('../libs/post')
var exists = require('../libs/exists')

describe('tumblr', function () {
  describe('post', function () {
    it('should works', function (done) {
      post({
        id: 1,
        title: 'test',
        url: 'http://www.example.com',
        date: new Date().toISOString(),
        description: 'This link is generated by stars-tumblr unit test'
      }, function(err) {
        if (err) return done(err)

        exists(1, function (err, exists) {
          if (err) return done(err)

          exists.should.be.true()
          done()
        })
      })
    })
  })
})
